/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package smart.lamp;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.*;
import java.awt.event.*;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Denny Cahyo
 */


public class SmartLampGUI extends javax.swing.JFrame {

    
    /**
     * Creates new form SmartLamp
     */
    History h = new History();
    public SmartLampGUI() {
        initComponents();
//        Date now = new Date();
//        Calendar cal = Calendar.getInstance();
//        SimpleDateFormat frm = new SimpleDateFormat("dd MMMM yyyy HH:mm:ss");
//        String tgl = frm.format(now);
//        tanggal.setText(tgl);
//        Timer timer = new Timer(WIDTH, null);
//        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
//        String wkt = sdf.format(timer);
//        waktu.setText(wkt);
        currentdate();
    }
    public void currentdate(){


            Thread clock= new Thread(){
                public void run(){
                    for(;;){
            Calendar cal= new GregorianCalendar();

            int mo = cal.get(Calendar.MONTH);
            int ye = cal.get(Calendar.YEAR);
            int d = cal.get(Calendar.DAY_OF_MONTH);
            tanggal.setText(+d+" - "+(mo+1)+" - "+ye);


            int se=cal.get(Calendar.SECOND);
            int min = cal.get(Calendar.MINUTE);
            int ha = cal.get(Calendar.HOUR_OF_DAY);
            waktu.setText(+ha+" : "+(min)+" : "+se);
                        try {
                            sleep(1000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(SmartLampGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }
            };
            clock.start(); 
    }
    private void tampilHistory(){
        Database db2 = new Database();
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID History");
        tbl.addColumn("Tanggal");
        tbl.addColumn("Waktu");
        TabelHistory.setModel(tbl);
        try{
            ResultSet rs = db2.getData("select * from history");
            while(rs.next()){
                tbl.addRow(new Object[]{
                rs.getString("id"),
                rs.getString("tanggal"),
                rs.getString("waktu")
            });
                TabelHistory.setModel(tbl);
            }
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
        }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Utama = new javax.swing.JPanel();
        Masuk = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LampuPintar = new javax.swing.JPanel();
        lampuMati = new javax.swing.JLabel();
        lampuNyala = new javax.swing.JLabel();
        adaBtn = new javax.swing.JLabel();
        tdkAdaBtn = new javax.swing.JLabel();
        historyBtn = new javax.swing.JLabel();
        exitBtn = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        History = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelHistory = new javax.swing.JTable();
        backBtn = new javax.swing.JLabel();
        clearBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Utama.setLayout(new java.awt.CardLayout());

        Masuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/4.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        Masuk.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 360, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/1.JPG"))); // NOI18N
        Masuk.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Utama.add(Masuk, "card3");

        LampuPintar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lampuMati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/8.png"))); // NOI18N
        LampuPintar.add(lampuMati, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, -10, -1, -1));

        lampuNyala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/7.png"))); // NOI18N
        LampuPintar.add(lampuNyala, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, -10, -1, -1));

        adaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/9.png"))); // NOI18N
        adaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adaBtnMouseClicked(evt);
            }
        });
        LampuPintar.add(adaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 340, 350));

        tdkAdaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/2.png"))); // NOI18N
        tdkAdaBtn.setToolTipText("");
        tdkAdaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdkAdaBtnMouseClicked(evt);
            }
        });
        LampuPintar.add(tdkAdaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        historyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/6.png"))); // NOI18N
        historyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyBtnMouseClicked(evt);
            }
        });
        LampuPintar.add(historyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, 70));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/5.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        LampuPintar.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        tanggal.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        LampuPintar.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 160, 30));

        waktu.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        LampuPintar.add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/3.JPG"))); // NOI18N
        LampuPintar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));

        Utama.add(LampuPintar, "card2");

        History.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID History", "Tanggal", "Waktu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelHistory);

        History.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 790, 450));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/11.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        History.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/12.png"))); // NOI18N
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBtnMouseClicked(evt);
            }
        });
        History.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart/lamp/10.png"))); // NOI18N
        jLabel4.setToolTipText("");
        History.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Utama.add(History, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        LampuPintar.setVisible(true);
        Masuk.setVisible(false);
        History.setVisible(false);
        lampuMati.setVisible(true);
        lampuNyala.setVisible(false);
        adaBtn.setVisible(true);
        tdkAdaBtn.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void adaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adaBtnMouseClicked
        // TODO add your handling code here:
        lampuMati.setVisible(false);
        lampuNyala.setVisible(true);
        adaBtn.setVisible(false);
        tdkAdaBtn.setVisible(true);
        String Tgl = tanggal.getText();
        String Wkt = waktu.getText();
        Database db = new Database();
        try{
            String sql = "SELECT MAX(right(id,2)) AS no FROM history";
            ResultSet rs = db.getData(sql);
            while(rs.next()){
                if(rs.first() == false){
                    String ID = "H01";
                    h.saveHistory(ID,Tgl, Wkt);
                    //LokasiTxtIDLokasi.setText("L001");
                }else{
                    rs.last();
                    int noID = rs.getInt(1) + 1;
                    String no = String.valueOf(noID);
                    int noLong = no.length();
                    for(int a=0;a<2-noLong;a++){
                        no = "0" + no;
                    }
                    String ID = ("H" + no);
                    h.saveHistory(ID,Tgl, Wkt);
                    //LokasiTxtIDLokasi.setText("L" + no);
                }
            }
            rs.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_adaBtnMouseClicked

    private void tdkAdaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdkAdaBtnMouseClicked
        // TODO add your handling code here:
        lampuMati.setVisible(true);
        lampuNyala.setVisible(false);
        adaBtn.setVisible(true);
        tdkAdaBtn.setVisible(false);
    }//GEN-LAST:event_tdkAdaBtnMouseClicked

    private void historyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyBtnMouseClicked
        // TODO add your handling code here:
        LampuPintar.setVisible(false);
        Masuk.setVisible(false);
        History.setVisible(true);
        tampilHistory(); 
    }//GEN-LAST:event_historyBtnMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        LampuPintar.setVisible(true);
        Masuk.setVisible(false);
        History.setVisible(false);
    }//GEN-LAST:event_backBtnMouseClicked

    private void clearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseClicked
        // TODO add your handling code here:
        h.resetTable();
        tampilHistory();
    }//GEN-LAST:event_clearBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartLampGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartLampGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartLampGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartLampGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartLampGUI().setVisible(true);
           }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel History;
    private javax.swing.JPanel LampuPintar;
    private javax.swing.JPanel Masuk;
    private javax.swing.JTable TabelHistory;
    private javax.swing.JPanel Utama;
    private javax.swing.JLabel adaBtn;
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel clearBtn;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel historyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lampuMati;
    private javax.swing.JLabel lampuNyala;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel tdkAdaBtn;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
